#ifndef KCM_ILI9341_FONT_H
#define KCM_ILI9341_FONT_H

/***************************************************************************************
   kcm_ili9341_font.h — supplies the ILI9341_t3_font_t type for the converted
   KCMk1 fonts in this directory (generated by tfont_to_ili9341.py).

   INTEGRATION POINT
   -----------------
   The ILI9341_t3_font_t struct is normally provided by the installed display
   library (PaulStoffregen ILI9341_t3 / ILI9341_fonts, reused by the wwatson4506
   RA8876 GFX library). We prefer that definition when its header is present so
   there is exactly one struct definition in the build. If none of the known
   headers are found, we fall back to the canonical layout below.

   If your RA8876 GFX library provides the struct under a different header name,
   add it to the __has_include list (or just #include it before the font .c files).
****************************************************************************************/

#include <stdint.h>

/***************************************************************************************
   GLYPH DATA BELONGS IN FLASH
   On Teensy 4 the linker puts plain `const` arrays into .data, which lives in DTCM --
   the data half of the 512 KB FlexRAM that ITCM is also carved out of. Seventeen fonts
   is ~189 KB of glyph data, which was nearly the whole of that half: a build measured
   .data at 195,264 bytes against a DTCM allowance of 196,608, leaving nothing for the
   stack and making teensy_size fail outright rather than report it.

   Flash is memory-mapped on this part, so moving the arrays there is purely a section
   attribute -- the renderer dereferences the same pointers, with no pgm_read_* dance
   and no code change. The cost is that glyph fetches go through the FlexSPI cache
   rather than DTCM, which is what PROGMEM exists for.

   Defined as a no-op off-target so the host test harnesses still compile these files.
****************************************************************************************/
#ifndef KCM_FONT_FLASH
  #if defined(__IMXRT1062__)
    #define KCM_FONT_FLASH __attribute__((section(".progmem")))
  #else
    #define KCM_FONT_FLASH
  #endif
#endif



// The font .c files in this directory are BOTH #included into the C++ display
// code AND compiled standalone by Arduino as C translation units. The RA8876/
// ILI9341_t3 struct headers are C++-only, so only pull them in under C++; a
// standalone C compile uses the pure-C fallback struct below (same layout, so
// the unused C copy is ABI-identical and harmless).
#ifdef __cplusplus
  #if defined(__has_include)
    // wwatson4506 TeensyRA8876-GFX-Common provides the struct here (pulled in via
    // KCM_Display.h -> RA8876_t41_p.h -> RA8876_common.h before this header).
    #if __has_include(<ILI9341_fonts.h>)
      #include <ILI9341_fonts.h>
      #define KCM_ILI9341_FONT_T_PROVIDED 1
    #elif __has_include(<ILI9341_t3.h>)
      #include <ILI9341_t3.h>
      #define KCM_ILI9341_FONT_T_PROVIDED 1
    #elif __has_include(<ILI9341_t3_font.h>)
      #include <ILI9341_t3_font.h>
      #define KCM_ILI9341_FONT_T_PROVIDED 1
    #elif __has_include(<ili9341_t3_font.h>)
      #include <ili9341_t3_font.h>
      #define KCM_ILI9341_FONT_T_PROVIDED 1
    #endif
  #endif
#endif

#ifndef KCM_ILI9341_FONT_T_PROVIDED
// Canonical ILI9341_t3 font descriptor. Field order/types must match the library
// that renders these fonts — do not reorder.
typedef struct {
  const unsigned char *index;
  const unsigned char *unicode;
  const unsigned char *data;
  unsigned char version;
  unsigned char reversed;
  unsigned char index1_first;
  unsigned char index1_last;
  unsigned char index2_first;
  unsigned char index2_last;
  unsigned char bits_index;
  unsigned char bits_width;
  unsigned char bits_height;
  unsigned char bits_xoffset;
  unsigned char bits_yoffset;
  unsigned char bits_delta;
  unsigned char line_space;
  unsigned char cap_height;
} ILI9341_t3_font_t;
#endif

#endif // KCM_ILI9341_FONT_H
