#ifndef KCM_ILI9341_FONT_H
#define KCM_ILI9341_FONT_H

/***************************************************************************************
   kcm_ili9341_font.h — supplies the ILI9341_t3_font_t type for the converted
   KCMk1 fonts in this directory (generated by tfont_to_ili9341.py).

   INTEGRATION POINT
   -----------------
   The ILI9341_t3_font_t struct is normally provided by the installed display
   library (PaulStoffregen ILI9341_t3 / ILI9341_fonts, reused by the wwatson4506
   RA8876 GFX library). We prefer that definition when its header is present so
   there is exactly one struct definition in the build. If none of the known
   headers are found, we fall back to the canonical layout below.

   If your RA8876 GFX library provides the struct under a different header name,
   add it to the __has_include list (or just #include it before the font .c files).
****************************************************************************************/

#include <stdint.h>

#if defined(__has_include)
  #if __has_include(<ILI9341_t3.h>)
    #include <ILI9341_t3.h>
    #define KCM_ILI9341_FONT_T_PROVIDED 1
  #elif __has_include(<ILI9341_t3_font.h>)
    #include <ILI9341_t3_font.h>
    #define KCM_ILI9341_FONT_T_PROVIDED 1
  #elif __has_include(<ili9341_t3_font.h>)
    #include <ili9341_t3_font.h>
    #define KCM_ILI9341_FONT_T_PROVIDED 1
  #endif
#endif

#ifndef KCM_ILI9341_FONT_T_PROVIDED
// Canonical ILI9341_t3 font descriptor. Field order/types must match the library
// that renders these fonts — do not reorder.
typedef struct {
  const unsigned char *index;
  const unsigned char *unicode;
  const unsigned char *data;
  unsigned char version;
  unsigned char reversed;
  unsigned char index1_first;
  unsigned char index1_last;
  unsigned char index2_first;
  unsigned char index2_last;
  unsigned char bits_index;
  unsigned char bits_width;
  unsigned char bits_height;
  unsigned char bits_xoffset;
  unsigned char bits_yoffset;
  unsigned char bits_delta;
  unsigned char line_space;
  unsigned char cap_height;
} ILI9341_t3_font_t;
#endif

#endif // KCM_ILI9341_FONT_H
